### ISSUE TITLE
Dependency error when building Cloud Function

### ISSUE THREAD

**Issue by coachtinho** [GoogleCloudPlatform/pubsub2inbox#14]
When deploying this module, the building of the Cloud Function throws an error related to a package not being pinned in `requirements.txt`.
![image](https://user-images.githubusercontent.com/33258760/209782284-abe83311-f579-419f-a16a-22ba85e3b512.png)

I know this error did not happen in the past, so I ran `git bisect` and determined that the commit that introduced this behavior was [Move requirements to use fully resolved set of dependencies plus enforce using hashes](https://github.com/GoogleCloudPlatform/pubsub2inbox/commit/ee645c8802d1b3873ef15b776834a5226f3d3efb).

I ran the `pip-compile` command mentioned at the top of `requirements.txt` and came across a warning for this very error.
![Pasted image 20221227160743](https://user-images.githubusercontent.com/33258760/209782885-1741628d-bd59-47b9-88f1-b745969483b2.png)

Adding the `--allow-unsafe` flag to the command did remove the warning, but the build error when deploying the Cloud Function remained.

**Comment by rosmo** [comment]
Thanks, I've seen that before but weirdly it doesn't happen on the container build. What Python version do you have?

**Comment by coachtinho** [comment]
On the Cloud Function, "python38". However, now that you mentioned it, I noticed that `requirements.txt` was generated using Python 3.9, and when I ran `pip-compile` myself, I used Python 3.10. Maybe it's related to that.

**Comment by rosmo** [comment]
It wasn't a Python issue, but some additional dependencies needed to be pinned and `--allow-unsafe` flag to be passed. I've fixed it now and also improved the Terraform code a bit.

**Comment by coachtinho** [comment]
It's working fine now. Thank you!

Closing this issue.

**Comment by coachtinho** [comment]
I'm running into this issue again. I tried updating the branch with your most recent changes but it didn't work. Also tried running the `pip-compile` command again. The error message is the exact same as before, but it displays a different link for the `googleapis-common-protos` package:

`googleapis-common-protos<2.0dev,>=1.56.2 from https://files.pythonhosted.org/packages/76/b9/fc6a31a90e3c78cea00d209d48f1e5c6c9edc6b14f3039470c3f7fae60a1/googleapis_common_protos-1.57.1-py2.py3-none-any.whl (from google-api-core[grpc]==2.10.2->-r requirements.txt (line 194)); Error ID: 0ea8a540`

**Comment by rosmo** [comment]
Yeah, it's pretty strange. It seems to work fine when the pipeline builds the container or whenever I do it locally. I have `googleapis-common-protos` also both in `requirements.txt.in` and the generated `requirements.txt`. What Python runtime version are you using?

**Comment by coachtinho** [comment]
On my machine, I'm running Python 3.10. The Cloud Function is using "python38".

**Comment by rosmo** [comment]
Well, that was a bit of an issue. I think the root cause is because `pip-compile` generates a dependency to `googleapis-common-protos[grpc]` no matter how much you try to force it use the one without the grpc qualifier. I fixed it by manually editing the `requirements.txt` to remove the `[grpc]` part. I think it's a `pip` bug but you can't fix it inside the Cloud Function environment.

I've pushed the fix and tagged a new release 1.4.7.

(just leaving the comment here in case someone stumbled upon this by search)

**Comment by rosmo** [comment]
@coachtinho Did you get this to work?

**Comment by coachtinho** [comment]
Sorry for the late response, I've been away for a while. Just tested it and seems to be working properly.

Thank you for the updates, closing the issue.
